# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'mainnet-tracker'
    static_configs:
    - targets: ['34.81.167.141:8080']

  - job_name: 'mainnet-node-0'
    static_configs:
    - targets: ['104.199.237.250:8080']

  - job_name: 'mainnet-node-1'
    static_configs:
    - targets: ['34.145.38.202:8080']

  - job_name: 'mainnet-node-2'
    static_configs:
    - targets: ['34.124.150.134:8080']

  - job_name: 'mainnet-node-3'
    static_configs:
    - targets: ['104.197.251.70:8080']

  - job_name: 'mainnet-node-4'
    static_configs:
    - targets: ['34.147.73.94:8080']

  - job_name: 'mainnet-node-5'
    static_configs:
    - targets: ['35.189.186.17:8080']

  - job_name: 'mainnet-node-6'
    static_configs:
    - targets: ['35.247.53.79:8080']

  - job_name: 'mainnet-node-7'
    static_configs:
    - targets: ['35.240.128.131:8080']

  - job_name: 'mainnet-node-8'
    static_configs:
    - targets: ['34.123.204.9:8080']

  - job_name: 'mainnet-node-9'
    static_configs:
    - targets: ['34.90.126.190:8080']

